### ISSUE TITLE
Problems with electrical-file_concat

### ISSUE THREAD

**Issue by nholau** [elastic/puppet-logstash#287]
I update my logstash module and the electrical-file_concat is a dependecy but when I run puppet this error  appear:

Error: /Stage[main]/Logstash::Config/File_concat[ls-config]: Could not evaluate: undefined method `stat' for File_concat[ls-config]:Puppet::Type::File_concat

**Comment by jarpy** [comment]
I looks like the `stat` function definition was removed from `electrical-file_concat` in mid-2015.

https://github.com/electrical/puppet-lib-file_concat/commit/631bc2b1ccebc83aaae8035885549a18fd68d3cb#diff-d43b80a603ae2a2b525b57c2e6c0c429L166

Which version of `electrical-file_concat` are you running now?

Is it possible that there is also another version of `file_concat` in your environment. Perhaps `ispavailability/file_concat`?

https://forge.puppet.com/ispavailability/file_concat

Thanks.

**Comment by nholau** [comment]
I try it, but the latest version of logstash plugin needs electrical-file_concat.

**Comment by jarpy** [comment]
Yes. I thought the problem might have been either:

 - The wrong version `electrical-file_concat`.
 - The right version of `electrical-file_concat`, and also another file_concat module at the same time.

Both those things would be a problem.

What version of `electrical-file_concat` do you use?

**Comment by nholau** [comment]
Hi, 

I have a electrical-file_concat 1.0.1 and puppetlabs concat  1.2.5

**Comment by nholau** [comment]
It works with electrical-file_concat 1.0.0
